// Pages exports
export { default as Login } from './Login/Login';
export { default as Dashboard } from './Dashboard/Dashboard';
export { default as Welcome } from './Welcome/Welcome';
export { default as RoleAllocation } from './RoleAllocation/RoleAllocation';
export { default as AppraisalDashboard } from './Appraisal/AppraisalDashboard/AppraisalDashboard';
export { default as AppraisalHome } from './Appraisal/AppraisalHome/AppraisalHome';
export { default as AppraiseeCheckIn } from './Appraisal/AppraiseeCheckIn/AppraiseeCheckIn';
export { default as AppraiserCheckIn } from './Appraisal/AppraiserCheckIn/AppraiserCheckIn';
export { default as AdminPanel } from './Panel/AdminPanel/AdminPanel';
export { default as HrDashboard } from './Appraisal/AppraisalHRDashboard/HrDashboard';
export { default as AppariserUpdate } from './Appraisal/AppraisalHRDashboard/AppraiserUpdate/AppraiserUpdate';
export { default as Appraisalstatus } from './Appraisal/AppraisalHRDashboard/AppraisalStatus/AppraisalStatus';
export { default as AppealComittee } from './Appraisal/AppraisalHRDashboard/AppealComittee/AppealComittee';
export { default as ReportingReviewBulk } from './Appraisal/AppraisalHRDashboard/ReportingReviewBulk/ReportingReviewBulk';
export { default as ValidatorUpdateUtility } from './Appraisal/AppraisalHRDashboard/ValidatorUpdate/ValidatorUpdateUtility';
export { default as ExceptionDelection } from './Appraisal/AppraisalHRDashboard/ExceptionDelection/ExceptionDelection';
export { default as AppealDelection } from './Appraisal/AppraisalHRDashboard/AppealDelection/AppealDelection';
export { default as ModuleActiveInactiveDate } from './Appraisal/AppraisalHRDashboard/ModuleActiveInactiveDate/ModuleActiveInactiveDate';
export { default as AppraisalCheckInForm } from './Appraisal/AppraisalCheckInForm/AppraisalCheckInForm';
export { default as ExceptionHome } from './Appraisal/ExceptionHome/ExceptionHome';
export { default as ExceptionVerify } from './Appraisal/ExceptionVerify/ExceptionVerify';
export { default as ExceptionsList } from './Appraisal/ExceptionsList/ExceptionsList';
export { default as ExceptionValidations } from './Appraisal/ExceptionValidations/ExceptionValidations';
export { default as AppraiserCheckInDashboard } from './Appraiser/AppraiserDashboardCheckIn/AppraiserCheckInDashboard';
export { default as QuarterlyException } from './Appraisal/ExceptionQuarterly/QuarterlyException';
export { default as EmployeeExceptionList } from './Appraisal/EmployeeExceptionList/EmployeeExceptionList';
export { default as ReviewQuarterlyException } from './Appraisal/ExceptionReview/ReviewQuaterlyException';
export { default as EmployeeQuarterlyExceptions } from './Appraisal/QuarterlyException/EmployeeQuarterlyException';
export { default as EmployeeAppealList } from './Appeal/AnnualAppeal/EmployeeAppealList/EmployeeAppealList';
export { default as AppraiserDashboard } from './Appraiser/AppraiserDashboard/AppraiserDashboard';
export { default as AnnualAppraisalHome } from './Appraiser/Annual/AnnualAppraisalHome';
export { default as AppraiserAddAppraisal } from './Appraiser/AppraiserAddAppraisal/AppraiserAddAppraisal';
export { default as AppraiseeDashboard } from './Appraisee/AppraiseeDashBoard/AppraiseeDashboard';
export { default as AddAppeal } from './Appraisee/AppraiseeDashBoard/AddAppeal/Addappeal';
export { default as QuarterlyAppraisee } from './Appraisal/QuarterlyCheckIn/QuarterlyAppraisee';
export { default as QuaterlyAppraiseeCheckIn } from './Appraisal/QuarterlyCheckIn/QuaterlyAppraiseeCheckIn/QuaterAppraiseeCheckIn';
export { default as QuarterlyAppraiserBulk } from './Appraisal/AppraisalHRDashboard/QuarterlyAppraiserBulk/QuarterlyAppraiserBulk';
export { default as AppealDeletion } from './Appraisal/AppraisalHRDashboard/AppealDelection/AppealDelection';
export { default as ReviewerDashboard } from './Appraiser/ReviewerDashboard/ReviewerDashboard';
export { default as ReviewerMode } from './Appraiser/ReviewerMode/ReviewerMode';
export { default as AppealCommitteeReview } from './Appeal/AppealCommittee/AppealCommitteeReview/AppealCommitteeReview';
export { default as ReviewAppeal } from './Appeal/AnnualAppeal/ReviewAppeal/ReviewAppeal';
export {
  AnnualAppraisalReview,
  AnnualReview,
  AnnualReviewView,
} from './Appraisal/AppraisalCheckInForm/annual';
//export { AnnualAppraisalReview, AnnualReview } from './Appraisal/AppraisalCheckInForm/annual';
//export { default as QuaterlyAppraiserCheckIn } from './Appraisal/QuarterlyCheckIn/QuaterlyAppraiserCheckIn/QuaterlyAppraiserCheckIn';
export { default as ManageFiles } from './Skills/Admin/ManageFiles/ManageFiles';
export { default as GenerateDetailedReport } from './Skills/Admin/GenerateDetailedReport/GenerateDetailedReport';
export { default as GenerateIDPs } from './Skills/Admin/GenerateIDPs/GenerateIDPs';
export { default as SetConfiguration } from './Skills/Admin/SetConfiguration/SetConfiguration';
export { default as ProfilerLandingPage } from './Skills/ProfilerLandingPage/ProfilerLandingPage';
export { default as AdminLanding } from './Skills/Admin/AdminLanding/AdminLanding';
export { default as SkillsDashboard } from './Skills/Dashboard/Dashboard';
export { default as Guidelines } from './Skills/Dashboard/DashboardTabs/Guidelines/Guidelines';
//export {default as AnnualAppraisalReview, AnnualReview } from './Appraisal/';
export {default as QuaterlyAppraiserCheckIn} from './Appraisal/QuarterlyCheckIn/QuaterlyAppraiseeCheckIn/QuaterAppraiseeCheckIn';
export {default as ReportingAuthorityReviewBulk} from './Appraisal/AppraisalHRDashboard/ReportingAuthorityBulk/ReportingAuthorityReviewBulk';
//export {default as ReportingReviewBulk} from './Appraisal/AppraisalHRDashboard/ReportingReviewBulk/ReportingReviewBulk';